
// products action
export const FETCH_PRODUCT_LOADING="FETCH_PRODUCT_LOADING"
export const FETCH_PRODUCTS_LOADING="FETCH_PRODUCTS_LOADING"
export const FETCH_PRODUCTS_SUCCESS="FETCH_PRODUCTS_SUCCESS"
export const FETCH_PRODUCTS_ERROR="FETCH_PRODUCTS_ERROR"
export const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS"
export const FETCH_PRODUCT_ERROR="FETCH_PRODUCT_ERROR"

// cart actions
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const ADD_TO_CART="ADD_TO_CART"
export const CART_LOADING="CART_LOADING"
export const SAVE_SHIPPING_ADDRESS="SAVE_SHIPPING_ADDRESS"
export const SAVE_PAYMENT_METHOD="SAVE_PAYMENT_METHOD"

// orders action
export const CREATE_ORDER_LOADING="CREATE_ORDER_LOADING"
export const CREATE_ORDER_SUCCESS="CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_ERROR="CREATE_ORDER_ERROR"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_ERROR = "GET_ORDER_ERROR"


// users action
export const LOGIN_ERROR="LOGIN_ERROR"
export const LOGOUT="LOGOUT"
export const REGISTER_ERROR="REGISTER_ERROR"
export const ACTIVATION_ERROR="ACTIVATION_ERROR"
export const ACCESSTOKEN_ERROR="ACCESSTOKEN_ERROR"
export const USER_ERROR="USER_ERROR"
export const USER_UPDATE="USER_UPDATE"
export const USER_DELETE_ERROR="USER_DELETE_ERROR"
export const USER_DELETE="USER_DELETE"
export const USER_DELETE_LOADING= "USER_DELETE_LOADING"
export const UPDATE_ERROR="UPDATE_ERROR"
export const LOGIN_SUCCESS='LOGIN_SUCCESS'
export const ACCESSTOKEN_SUCCESS='ACCESSTOKEN_SUCCESS'
export const USER_LOADED='USER_LOADED'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const ACTIVATION_SUCCESS='ACTIVATION_SUCCESS'
export const LOADING='LOADING'
export const USERS_LIST_LOADING="USERS_LIST_LOADING"
export const USERS_LIST="USERS_LIST"
export const USERS_LIST_ERROR="USERS_LIST_ERROR"
export const USER_ITEM_LOADING= "USER_ITEM_LOADING"
export const  USER_ITEM = "USER_ITEM"
export const  USER_ITEM_ERROR= "USER_ITEM_ERROR"
export const USER_ITEM_UPDATE_ERROR="USER_ITEM_UPDATE_ERROR"
export const USER_ITEM_UPDATE="USER_ITEM_UPDATE"
export const USER_ITEM_UPDATE_LOADING= "USER_ITEM_UPDATE_LOADING"